"""initial

Revision ID: 0001
Revises:
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute(
        "CREATE EXTENSION IF NOT EXISTS pg_trgm"
    )  # needed by the GIN trigram indexes
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cities",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("name_normalized", sa.String(length=128), nullable=False),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lng", sa.Float(), nullable=True),
        sa.Column("listing_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        op.f("ix_cities_name_normalized"), "cities", ["name_normalized"], unique=False
    )
    op.create_table(
        "vehicle_catalog",
        sa.Column(
            "category",
            sa.Enum(
                "light",
                "heavy",
                "motorcycle",
                "rental",
                "classic",
                name="category",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("brand", sa.String(length=128), nullable=False),
        sa.Column("model", sa.String(length=192), nullable=False),
        sa.Column("trim", sa.String(length=255), nullable=False),
        sa.Column("trim_normalized", sa.String(length=255), nullable=False),
        sa.Column("listing_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "category", "trim", name="uq_vehicle_catalog_category_trim"
        ),
    )
    op.create_index(
        op.f("ix_vehicle_catalog_brand"), "vehicle_catalog", ["brand"], unique=False
    )
    op.create_index(
        "ix_vehicle_catalog_trim_trgm",
        "vehicle_catalog",
        ["trim_normalized"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"trim_normalized": "gin_trgm_ops"},
    )
    op.create_table(
        "listings",
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "light",
                "heavy",
                "motorcycle",
                "rental",
                "classic",
                name="category",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("catalog_id", sa.Uuid(), nullable=True),
        sa.Column("city_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("title_normalized", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("km", sa.Integer(), nullable=True),
        sa.Column("price", sa.BigInteger(), nullable=True),
        sa.Column(
            "gearbox",
            sa.Enum(
                "manual", "automatic", name="gearbox", native_enum=False, length=32
            ),
            nullable=True,
        ),
        sa.Column(
            "fuel",
            sa.Enum(
                "petrol",
                "dual_factory",
                "dual_aftermarket",
                "hybrid",
                "plugin_hybrid",
                "electric",
                "diesel",
                name="fuel",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("color", sa.String(length=64), nullable=True),
        sa.Column(
            "body_condition",
            sa.Enum(
                "intact",
                "no_paint",
                "minor_scratches",
                "partial_paint",
                "heavy_paint",
                "dropped",
                "accident",
                "original",
                "restored",
                name="bodycondition",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("insurance_months", sa.Integer(), nullable=True),
        sa.Column("vehicle_type", sa.String(length=64), nullable=True),
        sa.Column("is_dealer", sa.Boolean(), nullable=False),
        sa.Column("district", sa.String(length=128), nullable=True),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lng", sa.Float(), nullable=True),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("image_urls", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("thumbnail_urls", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column(
            "attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("est_price", sa.BigInteger(), nullable=True),
        sa.Column(
            "est_basis",
            sa.Enum(
                "trim_year",
                "trim_near_year",
                "model_year",
                "model_near_year",
                "none",
                name="estimatebasis",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("est_sample_size", sa.Integer(), nullable=False),
        sa.Column("km_factor", sa.Float(), nullable=False),
        sa.Column("insurance_factor", sa.Float(), nullable=False),
        sa.Column("diff_pct", sa.Float(), nullable=True),
        sa.Column("deal_score", sa.Integer(), nullable=True),
        sa.Column("price_suspect", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["catalog_id"],
            ["vehicle_catalog.id"],
        ),
        sa.ForeignKeyConstraint(
            ["city_id"],
            ["cities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    op.create_index(
        "ix_listings_category_catalog",
        "listings",
        ["category", "catalog_id"],
        unique=False,
    )
    op.create_index(op.f("ix_listings_city_id"), "listings", ["city_id"], unique=False)
    op.create_index(
        "ix_listings_title_trgm",
        "listings",
        ["title_normalized"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"title_normalized": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_listings_title_trgm",
        table_name="listings",
        postgresql_using="gin",
        postgresql_ops={"title_normalized": "gin_trgm_ops"},
    )
    op.drop_index(op.f("ix_listings_city_id"), table_name="listings")
    op.drop_index("ix_listings_category_catalog", table_name="listings")
    op.drop_table("listings")
    op.drop_index(
        "ix_vehicle_catalog_trim_trgm",
        table_name="vehicle_catalog",
        postgresql_using="gin",
        postgresql_ops={"trim_normalized": "gin_trgm_ops"},
    )
    op.drop_index(op.f("ix_vehicle_catalog_brand"), table_name="vehicle_catalog")
    op.drop_table("vehicle_catalog")
    op.drop_index(op.f("ix_cities_name_normalized"), table_name="cities")
    op.drop_table("cities")
    # ### end Alembic commands ###
